#if 0
//
// Generated by Microsoft (R) D3D Shader Disassembler
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// no Input
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// no Output
cs_5_0
dcl_globalFlags refactoringAllowed
dcl_uav_structured u0, 16
dcl_thread_group 1, 1, 1
store_structured u0.xyzw, l(0), l(0), l(1.000000,0,0,1.000000)
ret 
// Approximately 0 instruction slots used
#endif

const BYTE g_CSMain[] =
{
     68,  88,  66,  67, 180,  72, 
     15, 179, 198,  26, 133, 116, 
    148,  75,  33,  79, 243, 170, 
    116,  76,   1,   0,   0,   0, 
    180,   0,   0,   0,   3,   0, 
      0,   0,  44,   0,   0,   0, 
     60,   0,   0,   0,  76,   0, 
      0,   0,  73,  83,  71,  78, 
      8,   0,   0,   0,   0,   0, 
      0,   0,   8,   0,   0,   0, 
     79,  83,  71,  78,   8,   0, 
      0,   0,   0,   0,   0,   0, 
      8,   0,   0,   0,  83,  72, 
     69,  88,  96,   0,   0,   0, 
     80,   0,   5,   0,  24,   0, 
      0,   0, 106,   8,   0,   1, 
    158,   0,   0,   4,   0, 224, 
     17,   0,   0,   0,   0,   0, 
     16,   0,   0,   0, 155,   0, 
      0,   4,   1,   0,   0,   0, 
      1,   0,   0,   0,   1,   0, 
      0,   0, 168,   0,   0,  12, 
    242, 224,  17,   0,   0,   0, 
      0,   0,   1,  64,   0,   0, 
      0,   0,   0,   0,   1,  64, 
      0,   0,   0,   0,   0,   0, 
      2,  64,   0,   0,   0,   0, 
    128,  63,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
    128,  63,  62,   0,   0,   1
};
