#if 0
//
// Generated by Microsoft (R) D3D Shader Disassembler
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// no Input
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// no Output
cs_5_0
dcl_globalFlags refactoringAllowed
dcl_resource_structured t0, 8
dcl_resource_structured t1, 8
dcl_uav_structured u0, 8
dcl_input vThreadID.x
dcl_temps 2
dcl_thread_group 1, 1, 1
ld_structured_indexable(structured_buffer, stride=8)(mixed,mixed,mixed,mixed) r0.xy, vThreadID.x, l(0), t0.xyxx
ld_structured_indexable(structured_buffer, stride=8)(mixed,mixed,mixed,mixed) r0.zw, vThreadID.x, l(0), t1.xxxy
iadd r1.x, r0.z, r0.x
add r1.y, r0.w, r0.y
store_structured u0.xy, vThreadID.x, l(0), r1.xyxx
ret 
// Approximately 0 instruction slots used
#endif

const BYTE g_CSMain[] =
{
     68,  88,  66,  67,  36,  64, 
     60,  24, 235, 105, 236, 121, 
     54, 188,  89,  35, 204,  41, 
    143, 150,   1,   0,   0,   0, 
     92,   1,   0,   0,   3,   0, 
      0,   0,  44,   0,   0,   0, 
     60,   0,   0,   0,  76,   0, 
      0,   0,  73,  83,  71,  78, 
      8,   0,   0,   0,   0,   0, 
      0,   0,   8,   0,   0,   0, 
     79,  83,  71,  78,   8,   0, 
      0,   0,   0,   0,   0,   0, 
      8,   0,   0,   0,  83,  72, 
     69,  88,   8,   1,   0,   0, 
     80,   0,   5,   0,  66,   0, 
      0,   0, 106,   8,   0,   1, 
    162,   0,   0,   4,   0, 112, 
     16,   0,   0,   0,   0,   0, 
      8,   0,   0,   0, 162,   0, 
      0,   4,   0, 112,  16,   0, 
      1,   0,   0,   0,   8,   0, 
      0,   0, 158,   0,   0,   4, 
      0, 224,  17,   0,   0,   0, 
      0,   0,   8,   0,   0,   0, 
     95,   0,   0,   2,  18,   0, 
      2,   0, 104,   0,   0,   2, 
      2,   0,   0,   0, 155,   0, 
      0,   4,   1,   0,   0,   0, 
      1,   0,   0,   0,   1,   0, 
      0,   0, 167,   0,   0, 138, 
      2,  67,   0, 128, 131, 153, 
     25,   0,  50,   0,  16,   0, 
      0,   0,   0,   0,  10,   0, 
      2,   0,   1,  64,   0,   0, 
      0,   0,   0,   0,  70, 112, 
     16,   0,   0,   0,   0,   0, 
    167,   0,   0, 138,   2,  67, 
      0, 128, 131, 153,  25,   0, 
    194,   0,  16,   0,   0,   0, 
      0,   0,  10,   0,   2,   0, 
      1,  64,   0,   0,   0,   0, 
      0,   0,   6, 116,  16,   0, 
      1,   0,   0,   0,  30,   0, 
      0,   7,  18,   0,  16,   0, 
      1,   0,   0,   0,  42,   0, 
     16,   0,   0,   0,   0,   0, 
     10,   0,  16,   0,   0,   0, 
      0,   0,   0,   0,   0,   7, 
     34,   0,  16,   0,   1,   0, 
      0,   0,  58,   0,  16,   0, 
      0,   0,   0,   0,  26,   0, 
     16,   0,   0,   0,   0,   0, 
    168,   0,   0,   8,  50, 224, 
     17,   0,   0,   0,   0,   0, 
     10,   0,   2,   0,   1,  64, 
      0,   0,   0,   0,   0,   0, 
     70,   0,  16,   0,   1,   0, 
      0,   0,  62,   0,   0,   1
};
